Fix build of pecl-intl
Fix the build of pecl-intl port on 12.2-RELEASE-p10 as of 2021-12-13.

Fixes the following issues:

/opt/ports/php56/devel/pecl-intl/work-php56/intl-3.0.0/breakiterator/codepointiterator_internal.h:39:17:
error: virtual function 'operator==' has a different return type ('UBool' (aka 'signed char')) than the function it overrides (which has return type 'bool')
                virtual UBool operator==(const BreakIterator& that) const;
                        ~~~~~ ^
/usr/local/include/unicode/brkiter.h:127:18: note: overridden virtual function is here
    virtual bool operator==(const BreakIterator&) const = 0;
            ~~~~ ^

/opt/ports/php56/devel/pecl-intl/work-php56/intl-3.0.0/breakiterator/codepointiterator_internal.cpp:78:31:
error: return type of out-of-line definition of 'PHP::CodePointBreakIterator::operator==' differs from that in the declaration
UBool CodePointBreakIterator::operator==(const BreakIterator& that) const
~~~~                         ^
/opt/ports/php56/devel/pecl-intl/work-php56/intl-3.0.0/breakiterator/codepointiterator_internal.h:39:16:
note: previous declaration is here
                virtual bool operator==(const BreakIterator& that) const;
                        ~~~~ ^

By replacing `UBool` with `bool`.