Add freetype2-10.4
php56-gd fails to build with freetype 2.11.0 with the following error:

    configure: error: freetype-config not found.

By adding a freetype-config wrapper `pkg-config freetype2` it then fails with:

    php-5.6.40/ext/gd/gd.c:83:12: fatal error: 'ft2build.h' file not found

Therefore an older version freetype 2.10.4 is added (from freebsd-ports 2021Q3).